import React from 'react';
import Image from 'next/image';
import Head from 'next/head'
import Navbar from '@/components/Navbar';
import GridContainer from '@/components/GridLayout/GridContainer';
import Row from '@/components/GridLayout/Row';
import Column from '@/components/GridLayout/Column';
import Button from '@/components/Button';
import ArrowIcon from '../assets/icons/arrow-right.svg';
import styles from './Home.module.scss';

 const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>CoinSynch App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <section className={styles['hero-section']}>
          <GridContainer>
            <Row>
              <Column lg={6}>
                <h1 className={styles['hero-header']}>Lorem ipsum dolor sit amet, consectetur</h1>
                <h5 className={styles['hero-paragraph']}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam, purus sit amet luctus venenatis,
                  lectus magna fringilla urna, porttitor
                </h5>

                <div className={styles['button-wrapper']}>
                  <Button onClick={() => ''} text={<span>Sign up now <Image alt="Arrow Icon" src={ArrowIcon} /></span>} />
                </div>

                <div className={styles['hero-keywords-list']}>
                  <div className={styles['hero-keyword']}>Cryptos</div>
                  <div className={styles['hero-keyword']}>NFTs</div>
                  <div className={styles['hero-keyword']}>Games</div>
                </div>
              </Column>
            </Row>
          </GridContainer>

          <div className={styles['hero-footer-banner']} />
        </section>
      </main>
    </div>
  );
}

export default Home;
