import React from 'react';
import Head from 'next/head'
import Navbar from '@/components/Navbar';
import AboutUsSection from '@/components/Home/AboutUsSection';
import HeroSection from '@/components/Home/HeroSection';
import NewsletterSection from '@/components/Home/NewsletterSection';
import Footer from '@/components/Footer';

 const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>CoinSynch App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <HeroSection />

        <AboutUsSection />

        <NewsletterSection />
      </main>

      <Footer />
    </div>
  );
}

export default Home;
